/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheCarRouteImport } from './routes/the-car'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'

const TheCarRoute = TheCarRouteImport.update({
  id: '/the-car',
  path: '/the-car',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/experience': typeof ExperienceRoute
  '/partners': typeof PartnersRoute
  '/process': typeof ProcessRoute
  '/the-car': typeof TheCarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/experience': typeof ExperienceRoute
  '/partners': typeof PartnersRoute
  '/process': typeof ProcessRoute
  '/the-car': typeof TheCarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/experience': typeof ExperienceRoute
  '/partners': typeof PartnersRoute
  '/process': typeof ProcessRoute
  '/the-car': typeof TheCarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/experience'
    | '/partners'
    | '/process'
    | '/the-car'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apply' | '/experience' | '/partners' | '/process' | '/the-car'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/experience'
    | '/partners'
    | '/process'
    | '/the-car'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  ExperienceRoute: typeof ExperienceRoute
  PartnersRoute: typeof PartnersRoute
  ProcessRoute: typeof ProcessRoute
  TheCarRoute: typeof TheCarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-car': {
      id: '/the-car'
      path: '/the-car'
      fullPath: '/the-car'
      preLoaderRoute: typeof TheCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  ExperienceRoute: ExperienceRoute,
  PartnersRoute: PartnersRoute,
  ProcessRoute: ProcessRoute,
  TheCarRoute: TheCarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
